name: food_delivery
description: "A new Flutter project for G10"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.6
  toastification: ^2.1.0
  l: ^4.0.2
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^6.2.1
  image_picker: ^0.8.4+1
  cached_network_image: ^3.3.1
  lottie: ^3.1.2

  # State management
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.5.0+1

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.1

  # Navigation
  go_router: ^14.2.3

  # Map
  yandex_mapkit: ^3.4.0
  latlong2: ^0.9.0
  geolocator: ^11.1.0
  device_preview: ^1.2.0
  connectivity_plus: ^6.0.4
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  dart_code_metrics: ^4.19.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/image.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
